# Tensorflow fundamentals 

# Introduction to tensors

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.15.0'

# create tensor with tf.constant

In [3]:
scaler=tf.constant(1)
scaler


<tf.Tensor: shape=(), dtype=int32, numpy=1>

# number of dimension of tensor

In [4]:
scaler.ndim

0

# create a vector

In [5]:
vector=tf.constant([2,3,4])

In [6]:
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [7]:
vector.ndim

1

# create matrix

In [9]:
matrix=tf.constant([[23,45],[22,33]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 45],
       [22, 33]])>

In [10]:
matrix.ndim

2

# create tensor

In [16]:
tensor=tf.constant([[[23,44,55],[44,55,44]],[[55,44,33],[11,21,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[23, 44, 55],
        [44, 55, 44]],

       [[55, 44, 33],
        [11, 21, 12]]])>

In [17]:
tensor.ndim

3