# creating tensor with .variable ,
### In this we can change the value in tensor in future but this not happen in .constant method

In [1]:
import tensorflow as tf

In [2]:
changeble_tensor=tf.Variable([23,33])
unchangeble_tensor=tf.constant([32,22])
changeble_tensor,unchangeble_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([23, 33])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([32, 22])>)

In [3]:
changeble_tensor[0]=3

TypeError: 'ResourceVariable' object does not support item assignment

### for changing the value of tensor we use .assign fuction

In [4]:
changeble_tensor[0].assing=7


# Creating random tensor

### random tensors are tensors of some arbitory size which contain random numbers

## Creating two random (but the same ) tensors

In [5]:
random_tensor1=tf.random.Generator.from_seed(42)
random_tensor1=random_tensor1.normal(shape=(3,2))

random_tensor2=tf.random.Generator.from_seed(42)
random_tensor2=random_tensor2.normal(shape=(3,2))

In [6]:
random_tensor1,random_tensor2,random_tensor1==random_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## shuffle the order of elements in a tensor

### shuffling tensor valuable for whey you want to shuffle your data so that the inherent dosen't affect learning

In [7]:
non_shuffle=tf.constant([[10,4],[4,5],[6,7],[6,2]])
non_shuffle

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[10,  4],
       [ 4,  5],
       [ 6,  7],
       [ 6,  2]])>

In [12]:
shuffled=tf.random.shuffle(non_shuffle)
shuffled

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 6,  2],
       [10,  4],
       [ 4,  5],
       [ 6,  7]])>

### If we want our shaffled tensors to be in the same order, we've got to use gobal seed as well as operation level seed

In [22]:
tf.random.set_seed(45) #global seed
tf.random.shuffle(non_shuffle,seed=45) # operation-level seed

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 6,  2],
       [ 4,  5],
       [ 6,  7],
       [10,  4]])>

# Other ways to make tensor
## tf.ones

In [23]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [25]:
tf.ones(shape=(4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

## tf.zeros

In [24]:
tf.zeros([4,4])

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

## Turn numpy arrays into tensor
### The main difference between numpy array and tensorflow tensor is that the tensor can run on gpu

In [26]:
import numpy as np

In [27]:
numpy_a=np.arange(1,10,dtype=np.int32)
numpy_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
tf.constant(numpy_a,shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])>

NameError: name 'rank_4_tensor' is not defined