### Getting more information from tensors

#### Shape, Axis or Dimension, Rank, Size

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [3]:
rank_4_tensor.ndim,tf.size(rank_4_tensor).numpy(),rank_4_tensor.shape


(4, 120, TensorShape([2, 3, 4, 5]))

In [4]:
print("elements along first axis(0)",rank_4_tensor.shape[0])
print("elements along last axis(-1_",rank_4_tensor.shape[-1])


elements along first axis(0) 2
elements along last axis(-1_ 5


# Indexing Tensor

 ### Tensor can be Index just like a python list

In [5]:
rank_4_tensor[:2,:2,:1]

<tf.Tensor: shape=(2, 2, 1, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]]], dtype=float32)>

### Get the first element from each dimension from each index except for the final one

In [6]:
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

## Add extra dimension into the tensor

In [7]:
rank_5_tensor=rank_4_tensor[:,:,:,:, tf.newaxis] 
# or rank_5_tensor = rank_4_tensor[..., tf.newaxis]

In [8]:
rank_5_tensor

<tf.Tensor: shape=(2, 3, 4, 5, 1), dtype=float32, numpy=
array([[[[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
     

## Alternative to tf.newaxis


In [9]:
tf.expand_dims(rank_4_tensor,axis=2)

<tf.Tensor: shape=(2, 3, 1, 4, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]],



       [[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]], dtype=float32)>

# Manupulating Tensors

### ** Basic Operations **  + - * /

In [10]:
# You can add values to a tensor using the addition operation
tensor=tf.constant([[34,55,6],[5,5,6]])
tensor + 10


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[44, 65, 16],
       [15, 15, 16]])>

In [11]:
tensor *10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[340, 550,  60],
       [ 50,  50,  60]])>

## we can use tensorflow built in operation too 

In [12]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[340, 550,  60],
       [ 50,  50,  60]])>

# Matrix Multiplication
#### Matrix multiplication is nothing but dot product between rows of first matrix to the columns of second matrix

In [13]:
tf.matmul(tensor,[[10,10],[2,2],[5,5]])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[480, 480],
       [ 90,  90]])>

In [14]:
# Matrix multiplication with python operator
tensor@[[10,10],[2,2],[5,5]]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[480, 480],
       [ 90,  90]])>

In [15]:
tensor.shape

TensorShape([2, 3])

In [16]:
tensor@tf.reshape(tensor,shape=[3,2])


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1516, 2181],
       [ 230,  336]])>

In [17]:
tensor,tf.reshape(tensor,shape=[3,2])

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[34, 55,  6],
        [ 5,  5,  6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[34, 55],
        [ 6,  5],
        [ 5,  6]])>)

## Transpose of a matrix

In [18]:
tf.transpose(tensor)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[34,  5],
       [55,  5],
       [ 6,  6]])>

In [19]:
tensor@tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4217,  481],
       [ 481,   86]])>

### Main difference between transpose and reshape is that transpose flip the axises and reshape shuffles the tensors

#### Generally, while performing a matrix multiplication task on two tensors and one of the axes doesn't line up then you should perform transpose instead of reshaping it will satisfy the matrix multiplication rule 

# Change the data type of a tensor

In [20]:
#create a new tensor with default datatype
tensor=tf.constant([2.3,4.5])
tensor.dtype

tf.float32

In [23]:
# change from float32 to float16 (reduce precision)
tensor=tf.constant([2.3,4.5],dtype=tf.float16)
tensor.dtype

tf.float16