# Aggregating a Tensor

### Aggregating tensor=considering them from multiple values down to a smaller amount of value

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
tensor=tf.constant([-3,-4])
tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-3, -4])>

In [3]:
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

# Let's go through the following forms of aggregation
### 1. Get the minimum
### 2. Get the maximum
### 3. Get the mean of a tensor
### 4. Get the sum of a tensor

In [4]:
# create a random tensor
tensor=tf.constant(np.random.randint(0,100,size=50))
tensor

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([74,  9, 39, 22, 52, 53, 20, 20, 29, 19, 56, 62, 65, 75, 82, 30, 44,
       45, 88, 55,  9, 47,  5, 68, 26, 55, 27,  1, 58, 54,  3, 98,  4, 85,
       37, 60, 50, 16, 80,  0, 58, 20, 24, 11, 23, 43, 37, 95, 30, 82])>

In [5]:
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [6]:
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [7]:
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [8]:
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2145>

#### Find variance and standard deviation

In [15]:
import tensorflow_probability as tfp

In [16]:
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=715>

In [21]:
tf.math.reduce_variance(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=714.53>

In [20]:
tf.math.reduce_std(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.730694>

## find positional maximum and minimum of a tensor


In [22]:
tf.random.set_seed(42)
tensor=tf.random.uniform(shape=[52])

In [23]:
tensor

<tf.Tensor: shape=(52,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043,
       0.6073899 , 0.46523476], dtype=float32)>

In [24]:
# argmax return the position of the maximum value
tf.argmax(tensor)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [27]:
# argmin return the position of the minimum value
tf.argmin(tensor),tensor[tf.argmin(tensor)]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

# Squeezing tensor

In [28]:
tf.random.set_seed(42)
tensor=tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,1,1,50])
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255,
            0.03366041, 0.68467236, 0.74011743, 0.8724445 ,
            0.22632635, 0.22319686, 0.3103881 , 0.7223358 ,
            0.13318717, 0.5480639 , 0.5746088 , 0.8996835 ,
            0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
            0.6602763 , 0.33695042, 0.60141766, 0.21062577,
            0.8527372 , 0.44062173, 0.9485276 , 0.23752594,
            0.81179297, 0.5263394 , 0.494308  , 0.21612847,
            0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162,
            0.79873943, 0.66028714, 0.5871513 , 0.16461694,
            0.7381023 , 0.32054043]]]]]], dtype=float32)>

In [29]:
tensor.shape

TensorShape([1, 1, 1, 1, 1, 50])

In [31]:
tensor_squeeze=tf.squeeze(tensor)
tensor_squeeze.shape,tensor_squeeze

(TensorShape([50]),
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>)