# One-hot encoding

In [15]:
import tensorflow as tf
import numpy as np

In [6]:
some_val=tf.constant([0,1,2,3])


In [7]:
tf.one_hot(some_val,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [8]:
tf.one_hot(some_val,depth=4,on_value='i love deep learning',off_value='i also like to dance')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'i love deep learning', b'i also like to dance',
        b'i also like to dance', b'i also like to dance'],
       [b'i also like to dance', b'i love deep learning',
        b'i also like to dance', b'i also like to dance'],
       [b'i also like to dance', b'i also like to dance',
        b'i love deep learning', b'i also like to dance'],
       [b'i also like to dance', b'i also like to dance',
        b'i also like to dance', b'i love deep learning']], dtype=object)>

In [9]:
tensor=tf.range(1,10)

In [10]:
tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [11]:
tf.math.square(tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [12]:
tf.math.sqrt(tf.cast(tensor,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [14]:
tf.math.log(tf.cast(tensor,dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

# Tensor with numpy array

In [16]:
j=tf.constant(np.array([4,5,6.2,6.0]))
j

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([4. , 5. , 6.2, 6. ])>

#### numpy array use float64 as default datatype while tensor use float32